server:
    port: 8080
    context-path: #/sungang/
#    tomcat:
#      basedir: logs
#      accesslog:
#        enabled: true
#        directory: .

spring:
  application:
    name: genesis-demo    # 项目名称尽量用小写

# 日志
logging:
  config: classpath:logback-spring.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery1:8761/eureka/,http://discovery2:8762/eureka/
    healthcheck:
      enabled: true
  instance:
      preferIpAddress: true

