message: Dev Message.

datasource:
    name: test
    url: jdbc:mysql://localhost:3306/spring-cloud-test?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

#kafka:binder.brokers=192.168.2.193
#kafka.binder.zkNodes=192.168.2.193
#kafka.binder.defaultBrokerPort=9092
#kafka.binder.defaultZkPort=2181
#kafka.destination=mydest
#
#
#rabbitmq.address=192.168.2.193
#rabbitmq.username=rabbitmq
#rabbitmq.password=rabbitmq